optimization:
  adaptive_mutation: true
  blend_alpha: 0.5
  checkpoint_dir: checkpoints
  convergence_generations: 10
  convergence_min_fitness: 0.8
  crossover_probability: 0.7
  crossover_type: uniform
  early_stopping: true
  elitism_size: 2
  generations: 100
  log_level: INFO
  max_workers: 4
  mutation_decay_rate: 0.95
  mutation_distribution: gaussian
  mutation_probability: 0.2
  mutation_range: 0.2
  parallel_processing: true
  population_size: 50
  save_frequency: 10
  selection_pressure: 1.5
  tournament_size: 3
population_size: 100
