strategies:
  # Parametri generali validi per tutte le strategie
  general:
    risk_free_rate: 0.02
    transaction_costs: 0.001
    slippage: 0.0001
    position_size_limits:
      min: 0.01
      max: 1.0
    max_positions: 5
    max_correlation: 0.7

  # Configurazione TrendMomentumStrategy
  trend_momentum:
    name: "Trend Momentum Strategy"
    indicators: ["rsi", "macd", "bollinger"]
    position_sizing:
      method: "fixed"  # options: fixed, volatility_adjusted, kelly
      base_size: 1.0
    entry_conditions:
      rsi_oversold: 30
      rsi_overbought: 70
      macd_threshold: 0
      bollinger_deviation: 2.0
    exit_conditions:
      profit_target: 0.05
      stop_loss: 0.02
      trailing_stop: 0.015
    filters:
      min_volume: 1000000
      min_volatility: 0.01
      trend_strength: 25

  # Configurazione OptionsStrategy
  options:
    name: "Options Volatility Strategy"
    indicators: ["rsi", "bollinger", "atr"]
    position_sizing:
      method: "volatility_adjusted"
      base_size: 1.0
      volatility_multiplier: 0.5
    entry_conditions:
      rsi_thresholds:
        oversold: 30
        overbought: 70
      volatility_conditions:
        min_atr: 0.02
        atr_percentile: 75
      price_conditions:
        bb_threshold: 2.0
    exit_conditions:
      profit_target: 0.1
      stop_loss: 0.05
      time_decay_threshold: 0.7
    risk_management:
      max_vega_exposure: 0.2
      max_gamma_exposure: 0.1
      delta_neutral: true
    option_preferences:
      min_days_to_expiry: 30
      max_days_to_expiry: 60
      preferred_delta: 0.3
      iv_rank_min: 0.5